#!/bin/bash
# My compile script

if [ -z "$1" ]; then
	echo "Usage: compile sourcefiles (first sourcefile name used as output)";
	exit 1
fi

function getOutputName() {
	awk -F'.cpp' '{print $1}' <<< "$1"
}

output=$(getOutputName $1)

for file in $@
do 
	source+="$file "
done

if g++ -o $output -ggdb -pedantic-errors -Wall -Weffc++ -Wextra -Wconversion -Wsign-conversion -Wshadow $source -std=c++20; then
	exit 0
else
	exit 1
fi
