#!/bin/bash
# compile and run script

if [ -z "$1" ]; then 
	echo "Usage: cprun sourcefiles";
	exit 1
fi

function getOutputName() {
	awk -F'.cpp' '{print $1}' <<< "$1"
}

output=$(getOutputName $1)

# if everything is okay run, else print error code and exit
if compile $@; then
	./$output;
else
	exit 1
fi

# remove executable after running
rm ./$output
exit 0
